name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: project
      - name: Install
        run: |
          pip install -r requirements.txt
        working-directory: project
      - name: Build
        run: mkdocs build
        env:
          ENABLE_PDF_EXPORT: 1
        working-directory: project
      - name: deploy
        run: mkdocs gh-deploy --config-file ../project/mkdocs.yml --remote-branch master
        env:
          ENABLE_PDF_EXPORT: 1
